version: '3.7'

services:

  dev:
    container_name: hts-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4202:4200'

