version: '3.7'

services:

  prod:
    container_name: hts-prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    image: arupsarkardocker/hts-ng-docker-app
    ports:
      - '80:80'

